"""Add iot_session_id to bookings

Revision ID: a3c5cbe62fe8
Revises: c09b20211832
Create Date: 2025-12-05 10:18:56.296348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3c5cbe62fe8'
down_revision: Union[str, Sequence[str], None] = 'c09b20211832'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('iot_session_id', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'iot_session_id')
    # ### end Alembic commands ###
