"""initial_schema

Revision ID: c09b20211832
Revises: 
Create Date: 2025-11-21 16:55:31.395445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c09b20211832'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Enable required PostgreSQL extensions
    op.execute('CREATE EXTENSION IF NOT EXISTS citext')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spaces',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('building', sa.Text(), nullable=False),
    sa.Column('floor', sa.Text(), nullable=False),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'MAINTENANCE', name='spacestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('capacity > 0', name='check_capacity_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_space_building_floor', 'spaces', ['building', 'floor'], unique=False)
    op.create_index('idx_space_status', 'spaces', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', name='userstatus'), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('student_id', sa.Text(), nullable=True),
    sa.Column('department', sa.Text(), nullable=True),
    sa.Column('year_of_study', sa.SmallInteger(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('profile_image_url', sa.Text(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('year_of_study IS NULL OR (year_of_study >= 1 AND year_of_study <= 7)', name='check_year_of_study_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('student_id')
    )
    op.create_index('idx_user_email', 'users', ['email'], unique=False)
    op.create_index('idx_user_role_status', 'users', ['role', 'status'], unique=False)
    op.create_index('idx_user_student_id', 'users', ['student_id'], unique=False)
    op.create_table('utilities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index('idx_utility_key', 'utilities', ['key'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('space_id', sa.BigInteger(), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', 'COMPLETED', 'NO_SHOW', name='bookingstatus'), nullable=False),
    sa.Column('attendees', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_by', sa.BigInteger(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('check_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('attendees > 0', name='check_attendees_positive'),
    sa.CheckConstraint('end_time > start_time', name='check_end_after_start'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_booking_date_status', 'bookings', ['booking_date', 'status'], unique=False)
    op.create_index('idx_booking_datetime', 'bookings', ['booking_date', 'start_time', 'end_time'], unique=False)
    op.create_index('idx_booking_space_id', 'bookings', ['space_id'], unique=False)
    op.create_index('idx_booking_user_id', 'bookings', ['user_id'], unique=False)
    op.create_table('space_utilities',
    sa.Column('space_id', sa.BigInteger(), nullable=False),
    sa.Column('utility_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['utility_id'], ['utilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('space_id', 'utility_id')
    )
    op.create_table('user_penalties',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('booking_id', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'RESOLVED', 'EXPIRED', name='penaltystatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('points > 0', name='check_points_positive'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_penalty_status', 'user_penalties', ['status'], unique=False)
    op.create_index('idx_penalty_user_id', 'user_penalties', ['user_id'], unique=False)
    op.create_table('user_ratings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('rated_user_id', sa.BigInteger(), nullable=False),
    sa.Column('booking_id', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='check_rating_range'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rated_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rating_user_id', 'user_ratings', ['rated_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_rating_user_id', table_name='user_ratings')
    op.drop_table('user_ratings')
    op.drop_index('idx_penalty_user_id', table_name='user_penalties')
    op.drop_index('idx_penalty_status', table_name='user_penalties')
    op.drop_table('user_penalties')
    op.drop_table('space_utilities')
    op.drop_index('idx_booking_user_id', table_name='bookings')
    op.drop_index('idx_booking_space_id', table_name='bookings')
    op.drop_index('idx_booking_datetime', table_name='bookings')
    op.drop_index('idx_booking_date_status', table_name='bookings')
    op.drop_table('bookings')
    op.drop_index('idx_utility_key', table_name='utilities')
    op.drop_table('utilities')
    op.drop_index('idx_user_student_id', table_name='users')
    op.drop_index('idx_user_role_status', table_name='users')
    op.drop_index('idx_user_email', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_space_status', table_name='spaces')
    op.drop_index('idx_space_building_floor', table_name='spaces')
    op.drop_table('spaces')

    # Drop enums after tables are dropped
    sa.Enum(name='userrole').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='userstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='spacestatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='bookingstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='penaltystatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
